title: "Mohamed Nisath"
email: mohamed.nisath3@gmail.com
description: "Experienced IT professional specializing in IT administration, technical support, and system troubleshooting."
baseurl: ""
url: "https://nisath16.github.io"
github_username: "Nisath16"
theme: jekyll-theme-minimal
